[package]
name = "hardwarectl"
version = "0.1.0"
authors = ["Joshua Stone <joshua.gage.stone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
dbus = "0.8.2"

[profile.release]
lto = true
